core/accounts/urls.py
from django.urls import path, include
from . import views

app_name = "accounts"
urlpatterns = [
    # path("signup/", views.SignUpView.as_view(), name="signup"),
]

core/books/urls.py
from django.urls import path
from . import views


app_name = "books"
urlpatterns = [
    path("", views.BookListView.as_view(), name="book_list"),
    path("<uuid:pk>/", views.BookDetailView.as_view(), name="book_detail"),
    path("search/", views.SearchResultsListView.as_view(), name="search_results"),
]

core/core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from debug_toolbar.toolbar import debug_toolbar_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    # User management
    path("accounts/", include("allauth.urls")),

    # Local Apps
    # path("accounts/", include("accounts.urls")),
    path("", include("pages.urls")),
    path("books/", include("books.urls")),
]

if settings.SHOW_DEBUGGER_TOOLBAR:
    urlpatterns += [path('__debug__/', include('debug_toolbar.urls')),]



if settings.DEBUG:
    # add root static files
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    # add media static files
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

core/pages/urls.py
from django.urls import path
from . import views

app_name = 'pages'
urlpatterns = [
    path("", views.HomePageView.as_view(), name="home"),
    path("about/", views.AboutPageView.as_view(), name="about"),
]

core/accounts/models/profiles.py
from django.db import models
from ..validators import iranian_phone_number_validator


class Profile(models.Model):
    user = models.OneToOneField(
        "User", on_delete=models.CASCADE, related_name="user_profile"
    )
    first_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)
    phone_number = models.CharField(
        max_length=15, validators=[iranian_phone_number_validator]
    )
    avatar = models.ImageField(
        upload_to="accounts/profile/", default="profile/default.jpg"
    )

    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.user.email

    def get_fullname(self):
        if self.first_name or self.last_name:
            return f"{self.first_name} {self.last_name}"
        else:
            return "پروفایل خود را تکمیل کنید"

core/accounts/models/users.py
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin
from django.db import models
from django.utils.translation import gettext_lazy as _
from ..managers import UserManager


# Create your models here.
class User(AbstractBaseUser, PermissionsMixin):
    """
    Custom User Model by AbstractBaseUser
    """
    username = models.CharField(_("username"), max_length=150, blank=True)
    email = models.EmailField(_("email address"), unique=True)
    is_staff = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    is_verified = models.BooleanField(default=False)

    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    objects = UserManager()

    def __str__(self):
        return self.email

core/books/models.py
import uuid 
from django.db import models
from django.contrib.auth import get_user_model 
from django.urls import reverse


User = get_user_model()


class Book(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    title = models.CharField(max_length=250)
    author = models.CharField(max_length=250)
    price = models.DecimalField(max_digits=6, decimal_places=2)
    cover = models.ImageField(upload_to='covers/', blank=True)
    
    class Meta:
        indexes = [
            models.Index(fields=['id'], name="id_index"),
        ]
        permissions = [
        ("special_status", "Can read all books"),
        ]

    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse("books:book_detail", args=[str(self.id)])
    

class Review(models.Model):
    book = models.ForeignKey(Book, on_delete=models.CASCADE, related_name='reviews')
    review = models.CharField(max_length=255)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    
    def __str__(self):
        return f"{self.author} - {self.book.title}"

core/pages/models.py
from django.db import models

# Create your models here.

core/accounts/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import User


class UserCreationForm(UserCreationForm):
    """
    If you want to add something in future
    """

    class Meta:
        model = User
        fields = ("email",)


class UserChangeForm(UserChangeForm):
    """
    If you want to add something in future
    """

    class Meta:
        model = User
        fields = ("email",)

core/books/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.db.models import Q
from django.views.generic import ListView, DetailView
from django.utils.decorators import method_decorator
from django.views.decorators.cache import cache_page
from .models import Book


class BookListView(LoginRequiredMixin, ListView):
    model = Book
    template_name = "books/book_list.html"
    
    def get_queryset(self):
        return Book.objects.all()


@method_decorator(cache_page(60 * 15), name='dispatch')
class BookDetailView(LoginRequiredMixin, PermissionRequiredMixin, DetailView):
    model = Book
    template_name = "books/book_detail.html"
    permission_required = "books.special_status"
    
    def get_queryset(self):
        return Book.objects.prefetch_related('reviews__author',).all()
    

class SearchResultsListView(ListView):
    model = Book
    template_name = "books/search_results.html"
    
    def get_queryset(self):
        query = self.request.GET.get("q")
        return Book.objects.filter(Q(title__icontains=query) | Q(author__icontains=query))

core/pages/views.py
from django.shortcuts import render
from django.views.generic import TemplateView


class HomePageView(TemplateView):
    template_name = "pages/home.html"


class AboutPageView(TemplateView):
    template_name = "pages/about.html"

core/templates/base/_base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% include "base/_header_refrences.html" %}
    <title>{% block title %}Book Store{% endblock title %}</title>
</head>
<body>
    {% include "base/shared/header.html" %}
    <div class="container my-5">
        {% block content %}
        {% endblock content %}
    </div>

    {% include "base/_footer_refrences.html" %}
</body>
</html>

core/templates/base/_footer_refrences.html
{% load static %}

<!-- Custom Js -->
<script src="{% static 'js/main.js' %}"></script>

<!-- Bootstrap core JavaScript -->
<script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
<script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

core/templates/base/_header_refrences.html
{% load static %}   

<!-- Bootstrap CSS -->
<link rel="stylesheet" href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}">

<!-- Custom CSS -->
<link rel="stylesheet" href="{% static 'css/style.css' %}">

core/templates/base/shared/header.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container">
        <a class="navbar-brand" href="#"><img src="https://getbootstrap.com/docs/5.0/assets/brand/bootstrap-logo.svg" alt="" width="30" height="24" class="d-inline-block align-text-top">BookStore</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link {% if request.resolver_match.url_name == "home" %}active{% endif %}" aria-current="page" href="{% url "pages:home" %}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link {% if request.resolver_match.url_name == "about" %}active{% endif %}" href="{% url "pages:about" %}">About Us</a>
          </li>
          <li class="nav-item">
            <a class="nav-link {% if request.resolver_match.url_name == "book_list" %}active{% endif %}" href="{% url "books:book_list" %}">Books</a>
          </li>
        </ul>
        <form class="d-flex" action="{% url "books:search_results" %}" method="get">
            <input class="form-control me-2" type="search" name="q" placeholder="Search" aria-\
            label="Search" >
            <button class="btn btn-outline-success" type="submit">Search</button>
        </form>
      </div>
    </div>
</nav>

core/templates/books/book_detail.html
{% extends "base/_base.html" %}
{% block title %}Book Detail{% endblock title %}
{% block content %}
<div class="col-md-4" style="width: 18rem;">
    {% if object.cover %}
    <img src="{{ object.cover.url }}" class="card-img-top" alt="test">
    {% endif %}
    <h2><a href="">{{ object.title }}</a></h2>
    <p>Author: {{object.author}}</p>
    <p>Price: {{object.price}}</p>        
</div>
<div class="row">
    <h3>Reviews</h3>
    <ul>
    {% for review in object.reviews.all %}
    <li>{{ review.review }} ({{ review.author }})</li>
    {% endfor %}
    </ul>
</div>
{% endblock content %}

core/templates/books/book_list.html
{% extends "base/_base.html" %}
{% block title %}Books{% endblock title %}
{% block content %}
<div class="row">
  {% for object in object_list %}
  <div class="col-md-4 mb-4">
      <div class="card" style="width: 18rem;">
      {% if object.cover %}
      <img src="{{ object.cover.url }}" class="card-img-top" alt="test">
      {% endif %}
      <div class="card-body">
          <h5 class="card-title">{{ object.title }}</h5>
          <p><strong>Price:</strong> ${{object.price}}</p>
          <a href="{{ object.get_absolute_url }}" class="btn btn-primary">Read More</a>
      </div>
      </div>
  </div>
  {% endfor %}
  </div>
{% endblock content %}

core/templates/books/search_results.html
{% extends "base/_base.html" %}
{% block title %}Search{% endblock title %}
{% block content %}
<div class="row">
<h1>Search Results</h1>
{% for object in object_list %}
<div class="col-md-4 mb-4">
    <div class="card" style="width: 18rem;">
    {% if object.cover %}
    <img src="{{ object.cover.url }}" class="card-img-top" alt="test">
    {% endif %}
    <div class="card-body">
        <h5 class="card-title">{{ object.title }}</h5>
        <p><strong>Price:</strong> ${{object.price}}</p>
        <a href="{{ object.get_absolute_url }}" class="btn btn-primary">Read More</a>
    </div>
    </div>
</div>
{% endfor %}
</div>
{% endblock content %}

core/templates/pages/about.html
{% extends "base/_base.html" %}
{% block title %}About{% endblock title %}
{% block content %}
<h1>About Page</h1>
{% endblock content %}

core/templates/pages/home.html
{% extends "base/_base.html" %}
{% block title %}Homepage{% endblock title %}
{% block content %}
    <h1>Welcome to the Book Store</h1>
    <p>This is the homepage of the Book Store</p>
    {% if user.is_authenticated %}
    <p>Hi {{ user.email }}!</p>
    <p><a class="btn btn-danger" href="{% url 'account_logout' %}">Log Out</a></p>
    {% else %}
    <p>You are not logged in</p>
    <a class="btn btn-info" href="{% url 'account_login' %}">Log In</a>
    <hr>
    <a class="btn btn-warning" href="{% url 'account_signup' %}">Sign Up</a>
    {% endif %}
{% endblock content %}